### ISSUE TITLE
Invalid version string

### ISSUE THREAD

**Issue by kotakorange** [brandonwamboldt/utilphp#105]
I've tried to install via composer but return "Could not parse version constraint utilphp: Invalid version string "utilphp"

Any suggestion?

**Comment by xuqingfeng** [comment]
@kotakorange show the `composer command` you are running?

**Comment by kotakorange** [comment]
composer require brandonwambolt/utilphp

**Comment by xuqingfeng** [comment]
It's `brandonwamboldt` not `brandonwambolt`.

**Comment by kotakorange** [comment]
ah.. sory. my bad eyes. thank you for your assistants. @xuqingfeng
