### ISSUE TITLE
is_https does not work with SSL proxies like Pound or Varnish Hitch 

### ISSUE THREAD

**Issue by gnanet** [brandonwamboldt/utilphp#106]
https://github.com/brandonwamboldt/utilphp/blob/master/src/utilphp/util.php#L775

Most of the mentioned systems can add an extra header to the request which is usually:
> X_FORWARDED_PROTO = "https"

I agree that there is no standard (known to me) for this header-value solution, but common setups suggest the above example.

Extending the checks, to look for this header, and the right value would enable **is_https** to detect  SSL Proxy setups.

I found a possible solution here: http://amal.net/?p=3991

```
function is_ssl() {
    if ( isset($_SERVER['HTTPS']) ) {
        if ( 'on' == strtolower($_SERVER['HTTPS']) ) return true;
        if ( '1' == $_SERVER['HTTPS'] ) return true;
    } elseif ( isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && ( 'https' == strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) ) ) {
        return true;
    } elseif ( isset($_SERVER['X_FORWARDED_PROTO']) && ( 'https' == strtolower($_SERVER['X_FORWARDED_PROTO']) ) ) {
        return true;
    }
    return false;
}
```

**Comment by gnanet** [comment]
Removed the port checking part from the example code after reading #10

**Comment by brandonwamboldt** [comment]
@alihamze added this as an option to the existing function
