### ISSUE TITLE
Needs composer support

### ISSUE THREAD

**Issue by hopeseekr** [brandonwamboldt/utilphp#114]
This package needs composer support.

If I get spare time this weekend, I'll add it.

**Comment by SmetDenis** [comment]
Hi,
I'm sorry. What did you mean?

https://github.com/brandonwamboldt/utilphp/blob/master/composer.json
https://packagist.org/packages/brandonwamboldt/utilphp

**Comment by hopeseekr** [comment]
OUCH!@ I had a very outdated repo. I apologize!
