### ISSUE TITLE
util::_linkify & util::_linkify_callback both public methods ?

### ISSUE THREAD

**Issue by vlad-light** [brandonwamboldt/utilphp#42]
[util::_linkify()](https://github.com/brandonwamboldt/utilphp/blob/master/src/utilphp/util.php#L1440) & [util::_linkify_callback](https://github.com/brandonwamboldt/utilphp/blob/master/src/utilphp/util.php#L1493) both are public methods. Just typo or there are reasons for that ?

**Comment by brandonwamboldt** [comment]
Fixed, thanks
