### ISSUE TITLE
util::var_dump high memory consumption

### ISSUE THREAD

**Issue by GMacx3** [brandonwamboldt/utilphp#43]
hello,
I noticed that the function util :: var_dump () with large variable has a large RAM consumption.
We are talking about a relatively large object from a total of 75 properties (Smarty variables, as well as project-related variables).

Allowed memory size of 268435456 bytes exhausted (tried to allocate 551 bytes) in ../abnahme/core/classes/Util.class.php on line 230

We use an Apache web server with PHP 5.5.18 on a Ubuntu server.

**Comment by brandonwamboldt** [comment]
`util::var_dump` now supports recursive data structures so this shouldn't occur.
