### ISSUE TITLE
performance and licensing issues with `remove_accents`

### ISSUE THREAD

**Issue by pilif** [brandonwamboldt/utilphp#44]
Your implementation of `remove_accents` has been lifted off WordPress (https://github.com/WordPress/WordPress/blob/master/wp-includes/formatting.php#L822) which is licensed under the GPL. This means that as long as you're using their code, you have to release your library under the GPL too.

Also, the function is really inefficient as it builds that huge replacement table every time it's called. If you have to generate many slugs, you start to spend more and more time calling `chr()` instead of really doing something useful.

These replacement tables are static and you really don't need to generate them every time the function is called.

**Comment by brandonwamboldt** [comment]
For the time being, I've replaced the main replacement table with a hard coded array to improve performance, and removed the rest of the code as I couldn't quickly come up with a replacement of my own. I'll look into replacing properly this weekend.

Using a static array drops the avg time to process a string 10,000 times from 6.2 seconds to 1.3 seconds. Quite substantial.

**Comment by brandonwamboldt** [comment]
I found a nice MIT licensed project that does nice character replacement for non-ASCII characters. I've copied the relevant portion of the project to mine (with attribution). Performance is comparable (10,000 iterations in 1.2 seconds).

**Comment by pilif** [comment]
Much better :-)

Be careful though: The old method was working on Latin1-Input too while the new code only works correctly with utf-8 encoded input.

**Comment by brandonwamboldt** [comment]
Arghh, ok, I'll look at it some more this weekend. Apparently I need more comprehensive test suites too :)

**Comment by brandonwamboldt** [comment]
I've fixed it so it has the same functionality as before for latin strings, but no longer uses `chr()` so it's significantly faster.
