### ISSUE TITLE
Need safeguards against GPL infection

### ISSUE THREAD

**Issue by hopeseekr** [brandonwamboldt/utilphp#58]
I like UtilPHP. I also like how the project maintainer actively addresses pull requests and even includes a lot of them.

The main reason I can personally and corporately use UtilPHP is because it is permissively licensed under a non-copyleft license (currently the MIT License). But this could change, may have changed already, if just one function is committed from a GPL, LGPL, or APL licensed project.

Ideally, you would add language stating that only code which is specifically created for this project will be accepted, unless the submitter puts an appropriate source-of-origin comment in both the source code and the pull request. 

Also, it would be helpful to add a requirement that forbids code from viral (so-called "copyleft") licenses, like all of the Free Software Foundation licenses and even the Creative Commons ShareAlike licenses.

This is doubly important as UtilPHP is a library.

Thanks.

**Comment by brandonwamboldt** [comment]
I agree, but since I'm not a lawyer I'll have to do some research about the best way to do this (look into other projects a what not).

**Comment by hopeseekr** [comment]
My corporation is about to deliver utilphp to a client. I have tasked the developer on that project with doing a complete code audit of every utilphp method we utilize to ensure that none of them are from GPL projects. If the dev has time, we'll move on to other methods [really, it all needs to be certified].

We're going to post any infected methods here as we find them.

**Comment by brandonwamboldt** [comment]
Based on that I decided to browse through a bit as well. Both `add_query_arg` and `remove_query_arg` were lifted directly from WordPress. I've updated both of them by rewriting them a bit based on how I'd do it (`add_query_arg` is now 10% more efficient and `remove_query_arg` is 25% more efficient in my tests). 

However, I'm not a lawyer and don't actually know how different/similar the functions have to be for it to be considered different code.

**Comment by brandonwamboldt** [comment]
Hmm based on my research, I don't think my original changes were enough so I rewrote `add_query_arg`. It's not quite as efficient anymore, but it's significantly different from the WordPress implementation.

**Comment by hopeseekr** [comment]
GPL Tainted methods: maybe_serialize(), maybe_unserialize(), is_serialized(). Obtained from Wordpress. 

I'm of the opinion that all but is_serialized() fall under the "Only one way" copyright exclusion clause, except perhaps, their function names. Probably have to be renamed.

Function is_serialized() needs to be clean-room implemented (not looking at any GPL code).

A quick / and dirty / way to become compliant immediately would be to remove the methods from the code base until is_serialized() can be reimplemented.

**Comment by brandonwamboldt** [comment]
I've rewritten `is_serialized()` to use a far more basic check (basically does a few sanity checks first then just tries to unserialize data). This should now be exempt from the WordPress licensing, however, it could be potentially a lot slower for larger objects and also is a possible security risk when run on unsanitized user input so I'll work on a proper rewrite (have to look into the serialization format more in depth).

I've also rewritten `maybe_unserialize` to skip calling `is_serialized` for the moment to avoid duplicate `unserialize()` calls and just copied the logic into the function. Really not ideal, but I didn't want to add the overhead of two `unserialize()` calls. 

`maybe_serialize` should be exempt from copyright like you said.

**Comment by hopeseekr** [comment]
Man. Whomever thinks the GPL is "open source" needs to get their head checks. It's like saying Communism's forced appropriation of everyone's creations is the ultimate form of "Charity" :o

**Comment by brandonwamboldt** [comment]
I agree. I can't imagine releasing anything under the GPL. Way too restrictive.

**Comment by brandonwamboldt** [comment]
I'm also going to implement a policy of doing some investigation whenever a pull request introduces new functions to see if the functions are coming from another library and to ensure licensing is compatible. That should keep the library in good condition.
