### ISSUE TITLE
Pure PHP UTF-8 detection is broken

### ISSUE THREAD

**Issue by hopeseekr** [brandonwamboldt/utilphp#62]
The perfectly valid UTF-8 string, "\xC3\x9CTF-8 F\xC2\xB5\xC3\xB1" [ÜTF-8 Fµñ] is being improperly detected as invalid UTF-8 by the pure PHP UTF-8 detection routine.

Demo: http://sandbox.onlinephpfunctions.com/code/209ff179240e378a40f00f456cc49d2eb8bd821a
See PR #61 for the unit test code, etc.

**Comment by brandonwamboldt** [comment]
Fixed thanks to your PR!
