### ISSUE TITLE
array_get not doing what it should?

### ISSUE THREAD

**Issue by Cidro** [brandonwamboldt/utilphp#69]
Is it just me or the `array_get` function is just returning the value that you pass to it?

**Comment by brandonwamboldt** [comment]
It returns what you pass it unless you pass it an unset variable in which case it returns the second argument. Example:

```php
<?php

require 'util.php';

echo $_POST['somevar']; // PHP Notice:  Undefined index: somevar in /var/www/utilphp/test.php on line 5

echo util::array_get($_POST['somevar'], 'nothing set'); // Outputs "nothing set" with no notices
```
Does that answer your question?
