### ISSUE TITLE
Should var_dump_plain() be a protected method?

### ISSUE THREAD

**Issue by hopeseekr** [brandonwamboldt/utilphp#78]
`var_dump_plain()` is not listed in the documentation, and it seems to just be a worker for var_dump(). Should it be a protected method?

Also, I cannot easily use PHP's internal `var_dump()` with Postman for debugging REST responses, because when xdebug is installed, `var_dump()` returns HTML output. I could actually really use a HTML-stripped `var_dump()`, which `var_dump_plain()` sounds like it should provide.

**Comment by brandonwamboldt** [comment]
`var_dump_plain()` should definitely be a protected method. Also, despite the name, it generates HTML not plain text. I could probably convert my existing code to generate plain text pretty easily, to act as a plain `var_dump()` in environments where it's not available because of xdebug.

**Comment by brandonwamboldt** [comment]
Fixed via 7a1bf5d0ff000f362eb8f1369bf23b570f7c2bbf
