### ISSUE TITLE
Add xss function

### ISSUE THREAD

**Issue by ArrowBaZ** [brandonwamboldt/utilphp#82]
Hi,

It's a very cool lib, could you add a function against xss attack please ?

Cheers,
Arrowbaz.

**Comment by thenthdegree** [comment]
Using a library such as HTML purifier would be best in this situation IMHO. No point reinventing (rewriting)  the wheel.

http://htmlpurifier.org/

**Comment by brandonwamboldt** [comment]
Yeah, thinking over it I think adding XSS functionality is overkill for this library.
