### ISSUE TITLE
error example

### ISSUE THREAD

**Issue by 123Matthieu** [brandonwamboldt/utilphp#84]
already, thank you for this excellent library that saves time!
by cons there is a small bug in the example of the doc for xxlinkifyxx function

```
util :: Linkify ('this string: has a link to www.google.com');
=> Returns 'this string: has a link to www.google.com'
```

this returns the text without the link

I must specify the http:// for than the link is converted
```
> util :: Linkify ('this string: has a link to http://www.google.com');
> => Returns 'this string: has a link to <a href="http://wwww.google.com/" > http://www.google.com </a>'
```

**Comment by brandonwamboldt** [comment]
Thanks, I've fixed the documentation.
