### ISSUE TITLE
PHPUnit won't run after last patch

### ISSUE THREAD

**Issue by Newman101** [brandonwamboldt/utilphp#96]
Hi all, just to let you know: PHPUnit does not run any longer. 

Error message: 

--
➜  utilphp git:(master) ✗ phpunit
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

Cannot open file "/var/www/html/utilphp/vendor/autoload.php".

This started happening when I checked out the latest repository. 

Is it just my PHPUnit or is there something wrong with the repo unit testing? 

Thanks.

**Comment by brandonwamboldt** [comment]
Another user sent in a patch to make PHP unit start using the composer autoloader (helps ensure we don't break autoloading support, which has happened once). Simply run `composer install` from the project directory and you should be good to go.

I'll work on adding a better error message.

**Comment by brandonwamboldt** [comment]
Hey, I actually just went ahead and made the autoloader optional. If it's not present, it'll result in 1 skipped test.
